export const PERMISSIONS = {
  LEAVE: {
    VIEW_ALL: { method: 'get', path: '/leave' },
    VIEW_MY: { method: 'get', path: '/leave/my-leaves' },
    VIEW_USER: { method: 'get', path: '/leave/user/:userId' },
    VIEW_CALENDAR: { method: 'get', path: '/leave/calendar/view' },
    VIEW_PENDING: { method: 'get', path: '/leave/approvals/pending' },
    APPLY: { method: 'post', path: '/leave' },
    UPDATE: { method: 'patch', path: '/leave/:id' },
    DELETE: { method: 'delete', path: '/leave/:id' },
    APPROVE: { method: 'patch', path: '/leave/:id/approve' },
    APPROVE_MANAGER: { method: 'patch', path: '/leave/:id/approve/manager' },
    APPROVE_PM: { method: 'patch', path: '/leave/:id/approve/pm' },
    APPROVE_LEAD: { method: 'patch', path: '/leave/:id/approve/lead' },
    APPROVE_ADMIN: { method: 'patch', path: '/leave/:id/approve/admin' },
    REJECT: { method: 'patch', path: '/leave/:id/reject' },
    BALANCES: { method: 'get', path: '/leave/balance/:userId' },
    ALLOCATE: { method: 'post', path: '/leave/balance/allocate' },
    ALLOCATE_ALL: { method: 'post', path: '/leave/balance/allocate-all' },
    CARRY_OVER: { method: 'post', path: '/leave/balance/carry-over' },
  },
  WORKLOG: {
    VIEW_ALL: { method: 'get', path: '/worklogs' },
    VIEW_MY: { method: 'get', path: '/worklogs/user' },
    CREATE: { method: 'post', path: '/worklogs' },
    UPDATE: { method: 'patch', path: '/worklogs/:id' },
    UPDATE_DATE: { method: 'patch', path: '/worklogs/:id/date' },
    DELETE: { method: 'delete', path: '/worklogs/:id' },
    BULK_APPROVE: { method: 'patch', path: '/worklogs/bulk-approve' },
    BULK_REJECT: { method: 'patch', path: '/worklogs/bulk-reject' },
    ADMIN_VIEW: { method: 'get', path: '/worklogs/allworklog' },
    PROJECT_WORKLOGS: { method: 'get', path: '/projects/:id/worklogs' },
  },
  TASK: {
    VIEW_ALL: { method: 'get', path: '/tasks' },
    CREATE: { method: 'post', path: '/tasks' },
    UPDATE: { method: 'patch', path: '/tasks/:id' },
    DELETE: { method: 'delete', path: '/tasks/:id' },
    FIRST_VERIFY: { method: 'patch', path: '/tasks/first-verify' },
    SECOND_VERIFY: { method: 'patch', path: '/tasks/second-verify' },
    BULK_UPDATE: { method: 'patch', path: '/tasks/bulk-update' },
    MARK_COMPLETE: { method: 'patch', path: '/tasks/mark-complete' },
    RANKING_VIEW: { method: 'get', path: '/tasks-ranking' },
    RANKING_MANAGE: { method: 'patch', path: '/tasks-ranking' },
  },
  PROJECT: {
    VIEW_ALL: { method: 'get', path: '/projects' },
    CREATE: { method: 'post', path: '/projects' },
    UPDATE: { method: 'patch', path: '/projects/:id' },
    DELETE: { method: 'delete', path: '/projects/:id' },
    ASSIGN_USER: { method: 'post', path: '/projects/:id/users/assign' },
    RELEASE_USER: { method: 'patch', path: '/projects/:id/users/:userId/release' },
    AVAILABILITY: { method: 'get', path: '/projects/availability/users' },
  },
  DASHBOARD: {
    ATTENDANCE: { method: 'get', path: '/dashboard/attendance' },
    WORKING_TIME: { method: 'get', path: '/dashboard/working-time' },
    USERS: { method: 'get', path: '/dashboard/users' },
  },
  ADMIN: {
    MANAGE_ROLES: { method: 'get', path: '/roles' },
    MANAGE_PERMISSIONS: { method: 'get', path: '/permissions' },
    SETTINGS: { method: 'get', path: '/department' },
  },
  USER: {
    VIEW_ALL: { method: 'get', path: '/users' },
    CREATE: { method: 'post', path: '/users' },
    UPDATE: { method: 'patch', path: '/users/:id' },
    DELETE: { method: 'delete', path: '/users/:id' },
  },
  NOTICE_BOARD: {
    VIEW_ALL: { method: 'get', path: '/notice-board' },
    CREATE: { method: 'post', path: '/notice-board' },
    UPDATE: { method: 'patch', path: '/notice-board/:id' },
    DELETE: { method: 'delete', path: '/notice-board/:id' },
  }
} as const;
